steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/bomb:$COMMIT_SHA', '.']
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/bomb:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:cloudbuild_cache'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bomb'
      - '--image'
      - 'asia.gcr.io/$PROJECT_ID/bomb:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
      - '--port'
      - '2567'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '1'
      - '--cpu-throttling'

  # delete not use images
  # https://github.com/GoogleCloudPlatform/gcr-cleaner
  - name: 'us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
    args:
      - '-tag-filter-any'
      - '.+'
      - '-keep'
      - '2'
      - '-repo'
      - 'asia.gcr.io/$PROJECT_ID/bomb'
