name: Lint/Format

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install root modules
        run: npm ci

      - name: install frontend modules
        run: npm run install:frontend

      - name: install backend modules
        run: npm run install:backend

      - name: lint frontend
        run: npm run lint:frontend

      - name: lint backend
        run: npm run lint:backend

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
          only_changed: True
          commit_message: 'refactor: format code'
