name: Lint/Format

on:
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: install root modules
        run: npm ci

      - name: install frontend modules
        run: npm run install:frontend

      - name: lint frontend
        run: npm run lint:frontend

  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: install root modules
        run: npm ci

      - name: install backend modules
        run: npm run install:backend

      - name: lint backend
        run: npm run lint:backend

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
          # commit push時に他のCIの対象にするために自前のTOKENを使う
          token: "${{ secrets.BOT_ACCESS_TOKEN }}"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: install root modules
        run: npm ci

      - name: Prettify code
        run: npm run format

      - name: commit and push
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "refactor: format code"
          committer_name: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          push: true
